image: golang:1.19-alpine

before_script:
  - export REPO_NAME=`echo $CI_PROJECT_URL|sed 's/.*:\/\///g;'`
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - curl -sfL https://raw.githubusercontent.com/go-task/task/master/install-task.sh | sh -s -- -d -b /usr/local/bin
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b /usr/local/bin
  - go mod download

stages:
    - quality
    - test
    - build

format:
    stage: quality
    script:
      - task format

security:
    stage: quality
    script:
      - task security
    
test:     
    stage: test
    script:
      - task test

build:
    stage: build
    script:
      - task build
    artifacts:
      paths:
        - build
