# This file is a template, and might need editing before it works on your project.
image: grpc/go

before_script:
  - export REPO_NAME=`echo $CI_PROJECT_URL|sed 's/.*:\/\///g;'`
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b /usr/local/bin
  - go get

stages:
    - quality
    - test
    - build

format:
    stage: quality
    script:
      - ./usr/local/bin/task format

security:
    stage: quality
    script:
      - ./usr/local/bin/task security
    
test:     
    stage: test
    script:
      - ./usr/local/bin/task test

build:
    stage: build
    script:
      - ./usr/local/bin/task build
    artifacts:
      paths:
        - build
