# This file is a template, and might need editing before it works on your project.
image: grpc/go

before_script:
  - export REPO_NAME=`echo $CI_PROJECT_URL|sed 's/.*:\/\///g;'`
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go install github.com/go-task/task/v3/cmd/task@latest
  - go install github.com/securego/gosec/cmd/gosec@latest
  - go get

stages:
    - quality
    - test
    - build

format:
    stage: quality
    script:
      - task format

security:
    stage: quality
    script:
      - task security
    
test:     
    stage: test
    script:
      - task test

build:
    stage: build
    script:
      - task build
    artifacts:
      paths:
        - build
