version: "3"

vars:
  APP: go-bomd{{exeExt}}

tasks:

  clean:
    desc: Clean the project
    cmds:
      - rm -rf ./build

  test:
    desc: Test the project
    cmds:
      - go test -cover ./...

  format:
    desc: Format the project
    cmds:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)

  lint:
    desc: Lint the code
    cmds:
      - golangci-lint run ./...

  security:
    desc: Run gosec for project
    cmds:
      - gosec -quiet ./...

  build:
    deps: [clean]
    desc: Build the project
    cmds:
      - mkdir ./build
      - CGO_ENABLED=0 GOARCH=amd64 go build -ldflags="-w -s" -o ./build/{{.APP}} .
