name: Test

on:
  pull_request:
  push:

jobs:
  golangci-lint:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org
      - name: Test
        run: task test
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-fmt=text ./...'
  matrix-test:
    if: ${{ startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/hotfix')}}
    name: Test
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
        id: go
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org
      - name: Test
        run: task test
